### ISSUE TITLE
Kali Linux

### ISSUE THREAD

**Issue by avinashk028** [MasterDevX/Termux-Kali#1]
After installing kali Linux the start typing command doesn't open the Linux

**Comment by MasterDevX** [comment]
Can you show the output when trying to run Kali?

**Comment by ismailkhalouti** [comment]
cant open kali

**Comment by MasterDevX** [comment]
Looks like unsuccessfull installation. Have you tried to reinstall Kali or even Termux?

**Comment by Abkerian** [comment]
> Looks like unsuccessfull installation. Have you tried to reinstall Kali or even Termux?
Same problem
How to reinstall kali on termux ?

**Comment by MasterDevX** [comment]
> How to reinstall kali on termux ?

If you have no important files in Termux, you can simply try reinstalling Termux and then try to install Kali again.

**Comment by sarfaraz257** [comment]
I reinstated even termux but it gives the same error

**Comment by Mrunal-sudo** [comment]
Error after giving command ./start-kali.sh,,, and program not started 😭😭

**Comment by QXR9** [comment]
I have same error. I think its about proot

**Comment by QXR9** [comment]
> > How to reinstall kali on termux ?
> 
> If you have no important files in Termux, you can simply try reinstalling Termux and then try to install Kali again.
That didn't work. Have anyone solution that another? Please? I absolutely need kali-termux.

**Comment by QXR9** [comment]
> > How to reinstall kali on termux ?
> 
> If you have no important files in Termux, you can simply try reinstalling Termux and then try to install Kali again.

That didn't work. Have anyone solution that another? I absolately need kali on termux.

**Comment by MRH02** [comment]
give solution

**Comment by roguepullrequest** [comment]
PR #15 should fix this

**Comment by abhibhande** [comment]
Create **`tmp`** folder in **kali-fs** folder it will work

**Comment by 1nzl** [comment]
> Create **`tmp`** folder in **kali-fs** folder it will work

How ?
