### ISSUE TITLE
GhostNetCCC/TerMux-kali

### ISSUE THREAD

**Issue by GhostNetCCC** [MasterDevX/Termux-Kali#11]
Lerrn newbie

**Comment by GhostNetCCC** [comment]
$ ./start-kali.sh
proot warning: can't sanitize binding "kali-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/kali-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
$

**Comment by roguepullrequest** [comment]
PR #15 fixes this
