### ISSUE TITLE
Unable to locate package

### ISSUE THREAD

**Issue by Killer-Panda-007** [MasterDevX/Termux-Kali#14]
Unable to locate package wget & proot.
[[]()![Screenshot_20201017-143440.jpg](https://user-images.githubusercontent.com/71578712/96333228-4c7f3800-1086-11eb-865c-74788851931a.jpg)

**Comment by roguepullrequest** [comment]
Please ensure that your termux is updated and then try to install proot and wget. With lastest version fully updated termux this should work for you.
