### ISSUE TITLE
proot error

### ISSUE THREAD

**Issue by MirXaMohsin** [MasterDevX/Termux-Kali#18]
proot warning: can't sanitize binding "kali-fs/tmp": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/Termux-Kali/kali-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.

**Comment by MasterDevX** [comment]
Should be good for now, thanks to https://github.com/MasterDevX/Termux-Kali/pull/15
