### ISSUE TITLE
Installing not workling

### ISSUE THREAD

**Issue by up2smoke** [MasterDevX/Termux-Kali#4]
This script will install Kali Linux in Termux.

[*] Checking for RootFS...
[*] Detecting CPU architecture...
[*] Downloading RootFS (~70Mb) for arm64...
[*] Decompressing RootFS...
tar: This does not look like a tar archive

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[*] Creating startup script...
[*] Configuring Shebang...
[*] Setting execution permissions...
[*] Removing RootFS image...

Kali Linux was successfully installed!
You can now launch it by executing ./start-kali.sh command.

**Comment by JOFLIX** [comment]
The same issue here; just after hard reset the phone. I reinstalled this but Kali won't install

**Comment by roguepullrequest** [comment]
PR #15 should fix this.

**Comment by up2smoke** [comment]
> PR #15 should fix this.

Not working 

![IMG_20201018_223402](https://user-images.githubusercontent.com/35378113/96385122-1e871a00-1192-11eb-9374-6f69cb7cad06.jpg)

**Comment by roguepullrequest** [comment]
Please update if it was able to finally work. Thank-
