### ISSUE TITLE
404 error for tar file 'kali-rootfs.tar.gz' 

### ISSUE THREAD

**Issue by devashish234073** [MasterDevX/Termux-Kali#6]
wget to https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Rootfs/Kali/armhf/kali-rootfs-armhf.tar.gz -O kali-rootfs.tar.gz -q

IS NOT WORKING.
as a result emplty kali-fs is getting created

**Comment by devashish234073** [comment]
I was able to install Kali by doing a work around, I downloaded teh tar file from "https://github.com/EXALAB/Anlinux-Resources/tree/master/Rootfs/Kali/armhf", 

instead of the url generated by InstallKali.sh, then, commented the wget command in the InstallKali.sh 

and renamed the kali-rootfs-armhf.tar.gz to kali-rootfs.tar.gz

and then with InstallKali.sh I was able to install

**Comment by roguepullrequest** [comment]
PR #15 should fix this
